import {calculateThaiAt,ThaiAtGianDiLuc} from './thai-at/thai-at.js';
import {BatQuaiDrawer} from './renderer/batquai-drawer.js';

const $=id=>document.getElementById(id);let drawer;
function readInput(){return {year:+$('year').value,month:+$('month').value,day:+$('day').value,hour:+$('hour').value,minute:+$('minute').value,keType:$('keType').value}}
function card(title,value){return `<div class="summary-card"><b>${esc(title)}</b><div>${esc(typeof value==='string'?value:JSON.stringify(value,null,2))}</div></div>`}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function run(){try{$('engineStatus').textContent='Đang tính…';$('engineStatus').className='badge';const input=readInput();const result=calculateThaiAt(input);const gian=new ThaiAtGianDiLuc(result.t);if(!drawer)drawer=new BatQuaiDrawer($('batQuaiCanvas'));drawer.render(result.viewer);$('boardMeta').textContent=`${result.state.keType.name} · ${result.state.solar}`;$('summary').innerHTML=[card('Thái Ất',result.state.thaiAt),card('Cục',result.state.cuc),card('Chủ / Khách',result.state.chuKhach),card('Kế Thần',result.state.keThan),card('Văn Xương',result.state.vanXuong),card('Thủy Kích',result.state.thuyKich),card('Đại Du',result.state.daiDu),card('Tiểu Du',result.state.tieuDu),card('Gian Di Lục',gian.infoDaiDu())].join('');$('debug').innerHTML=result.trace.map(x=>`<div class="debug-line"><span class="debug-key">${esc(x.key)}</span>: ${esc(typeof x.value==='string'?x.value:JSON.stringify(x.value))}</div>`).join('');$('rawDebug').textContent=JSON.stringify({input,viewer:result.viewer,state:result.state,trace:result.trace},null,2);$('engineStatus').textContent='OK';$('engineStatus').className='badge ok'}catch(e){console.error(e);$('engineStatus').textContent='Lỗi';$('engineStatus').className='badge err';$('debug').innerHTML=`<div class="debug-line">${esc(e.stack||e.message||e)}</div>`}}
$('calculate').addEventListener('click',run);$('clearDebug').addEventListener('click',()=>{$('debug').innerHTML='';$('rawDebug').textContent=''});$('showRaw').addEventListener('change',e=>$('rawDebug').classList.toggle('hidden',!e.target.checked));run();
